[package]
name = "slcl"
version = "0.7.0"
edition = "2024"
published-at = "0xaff18bf6286047126901610d758d8fd111c9215a6e46abc704b6a0be838badd5"

[addresses]
slcl = "0xaff18bf6286047126901610d758d8fd111c9215a6e46abc704b6a0be838badd5"
sui = "0x2"
std = "0x1"

[environments]
testnet = "4c78adac"
devnet = "e9eed8f1"
mainnet = "35834a8a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
